server:
  port: 8000
spring:
  application:
    name: usyc-services
  datasource:
    url: jdbc:postgresql://localhost:5438/USYC_DB
    username: postgres
    password: 291000
    driver-class-name: org.postgresql.Driver
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
app:
  storage:
    qr-dir: ${QR_DIR:C:\usyc\qr}
  security:
    jwt:
      secret: "CAMBIA_ESTA_CLAVE_LARGA_LARGA_LARGA_32+_CHARS_MIN"
      minutes: 480
    cookie:
      name: "JWT"
      same-site: "Lax"   # Lax para swagger y navegación normal
      secure: false      # en local false; en prod true (HTTPS)
