server:
  port: 8000
spring:
  application:
    name: usyc-services
  datasource:
    url: jdbc:postgresql://localhost:5438/USYC_DB
    username: postgres
    password: 291000
    driver-class-name: org.postgresql.Driver
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
app:
  storage:
    qr-dir: ${QR_DIR:C:\usyc\qr}

